# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af330435cb21e3ef36d15049032459f200ea29877876c276d39e0e059839bf72ba90cb4815b9c2e7f93f27fcede50a003cfdc935d65f9192e5af81b73c147abf

test:
  secret_key_base: fd61e110cb8c45f9febc33ff188befc6c9e6c54e04ea6e6d72085a7ca9d5b5a675d02cb586bcb4b2d8453f3adaae3953cafd1828cf160d95330a06d787cda0ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
